{{ if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.name" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "<CHARTNAME>.selectorLabels" . | nindent 4 }}
  {{- with Values.service..ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
